modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="diamante"
version="${file.jarVersion}"
displayName="Diamante"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="diamante.png"
credits="Joe Mama"
authors="LegoMaster3650"
displayTest="MATCH_VERSION"
description='''
Diamonds are dying! This is my attempt to save them.
'''

[[dependencies.diamante]]
	modId="forge"
	mandatory=true
	versionRange="[43,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.diamante]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"

[[dependencies.diamante]]
	modId="goldenhopper"
	mandatory=false
	versionRange="[1.0.0,)"
	ordering="AFTER"
	side="BOTH"
